# Generated by Django 6.0.6 on 2026-06-27 14:45

import collections_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=collections_app.fields.SnowflakeIDField(default=collections_app.fields.generate_snowflake_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=collections_app.fields.SnowflakeIDField(default=collections_app.fields.generate_snowflake_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
